[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RAiD"
authors = [{name = "Shawn Ross", email = "shawn.ross@ardc.edu.au"}]
dynamic = ["version", "description"]
